1894: Revert upgrading Workflow module to 2.7
This also means we have to reapply patches.

Upgrading Workflow has introduced a range of other problems.

Creating a News node spawns errors:

- Workflow 1 cannot be loaded. Contact your system administrator. 

Workflow 1 cannot be loaded. Contact your system administrator.
Error: content 42 has no workflow attached. The data is not saved.
PDOException: SQLSTATE23000: Integrity constraint violation: 1048 Column
 'field_bpi_workflow_value' cannot be null: INSERT INTO 
{field_data_field_bpi_workflow} (entity_type, entity_id, revision_id, 
bundle, delta, language, field_bpi_workflow_value) i 
field_sql_storage_field_storage_write() (linje 514 af 
/var/aegir/platforms/ddb300rc2/modules/field/modules/field_sql_storage
/field_sql_storage.module).